name: "Nox (cross-arch)"
description: "Run a nox session for a particular architecture"
author: "Frequenz Energy-as-a-Service GmbH"

# Refer to the following link(s) for more information on inputs:
# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs
inputs:
  architecture:
    description: >
      The architecture to build the Docker image for example, `arm`, `arm64`,
      etc.

      Passed to the `frequenz-floss/gh-action-run-python-in-qemu` action,
      please consult the action for more details.
    required: true
  python_version:
    description: >
      The Python version to use, for example `3.11`, `3.12`, etc.

      Passed to the `frequenz-floss/gh-action-run-python-in-qemu` action,
      please consult the action for more details.
    required: true
    default: ""
  nox_session:
    description: >
      The nox session to run.
    required: true
  nox_dependencies:
    description: >
      The dependencies to install using `pip` to run `nox`. By default
      `".[dev-noxfile]"` is used, but projects not having any extra dependency
      to run nox can just use `"nox"`.

      Due to current limitations, values can't have spaces or other special
      characters interpreted by bash.
    required: false
    default: ".[dev-noxfile]"
  ubuntu_version:
    description: >
      The Ubuntu version to use, for example `20.04`, `22.04`, etc. Required
      unless `dockerfile` is provided.

      Passed to the `frequenz-floss/gh-action-run-python-in-qemu` action,
      please consult the action for more details.
    required: false
    default: ""
  dockerfile:
    description: >
      The Dockerfile to use to build the Docker image.

      Passed to the `frequenz-floss/gh-action-run-python-in-qemu` action,
      please consult the action for more details.
    required: false
    default: ""


# Refer to the following link(s) for more information on the composite run steps:
# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs
runs:
  using: "composite"
  steps:
    - name: Run nox in QEMU
      uses: frequenz-floss/gh-action-run-python-in-qemu@v0.x.x
      with:
        script: "${{ github.action_path }}/run-nox"
        pass_env: "NOX_SESSION=${{ inputs.nox_session }} NOX_DEPENDENCIES=${{ inputs.nox_dependencies }}"
        architecture: ${{ matrix.architecture }}
        ubuntu_version: ${{ inputs.ubuntu_version }}
        python_version: ${{ inputs.python_version }}
        dockerfile: ${{ inputs.dockerfile }}
