#!/bin/sh
# License: MIT
# Copyright © 2024 Frequenz Energy-as-a-Service GmbH
set -eu

echo "Nox dependencies: $NOX_DEPENDENCIES"
echo "Nox session: $NOX_SESSION"

python -I -m pip install $NOX_DEPENDENCIES
echo "Pip packages installed for running nox:"
python -I -m pip freeze

python -I -m nox --install-only -e "$NOX_SESSION"
. ".nox/$NOX_SESSION/bin/activate"
echo "Pip packages installed in nox environment:"
python -I -m pip freeze
deactivate

exec python -I -m nox -R -e "$NOX_SESSION" "$@"
